### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by ygitore** [yitbarekgitore/temperatureConvertor#10]
# User Story
As a user, I would like to see what the final result will look like

# AC
**WHEN** I open this ticket
**THEN** I should see wireframes in the comments with title('Temperature Converter') at the top of the page, input field with placeholder 'Enter number here' next convert label, on the third row on the left to label, and convert button background color green, reset button background color red and output here label. I would also like to see body background color lightgreen. 

# Dev Notes
* Create wireframes using Moqups
* Use snippet application in your computer to copy moqups and paste it in the comments field of this ticket.

**Comment by yitbarekgitore** [comment]
![image](https://user-images.githubusercontent.com/22806140/65057643-86888280-d938-11e9-8939-66f15bd5e60c.png)

**Comment by ygitore** [comment]
![image](https://user-images.githubusercontent.com/22806140/65886182-80939800-e361-11e9-89cc-7bf815592202.png)
